server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: nyamnyam-eureka-server-a5ef8-100122233-8a2cf10bd9d7.kr.lb.naverncp.com
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://nyamnyam-eureka-server-a5ef8-100122233-8a2cf10bd9d7.kr.lb.naverncp.com :8761/eureka/
    register-with-eureka: true
    fetch-registry: true